version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    target-branch: dev
    schedule:
      interval: weekly
    ignore:
      # ignore forked linters because of their versioning issues. TODO: fix it.
      - dependency-name: "github.com/golangci/*"
    reviewers:
      - troydota
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: dev
    schedule:
      interval: weekly
    reviewers:
      - troydota
  - package-ecosystem: docker
    directory: "/build"
    target-branch: dev
    schedule:
      interval: weekly
    reviewers:
      - troydota
  - package-ecosystem: gomod
    directory: "/scripts/gen_github_action_config"
    target-branch: dev
    schedule:
      interval: weekly
    reviewers:
      - troydota
  - package-ecosystem: npm
    directory: "/docs"
    target-branch: dev
    schedule:
      interval: monthly
    reviewers:
      - troydota
