level: info

tts_channel_id: 

redis:
  uri: redis://localhost/0
  task_set_key: tasks
  output_event: output

mongo:
  uri: mongodb://localhost
  database: tts

streamelements:
  enabled: true
  wss_url: wss://realtime.streamelements.com/socket.io/?cluster=main&EIO=3&transport=websocket
  auth_method: jwt
  auth_token: 

api_bind: 0.0.0.0:8888

cors: http://localhost:3000

twitch:
  client_id: 
  client_secret: 
  redirect_uri: http://localhost:8888/v1/twitch/callback
  bot_username: komodotroy
  bot_id: 614822347
  bot_control_channel: troydota
  whitelisted_accounts:
    - 121903137
    - 614822347
    - 133955304
    - 30816637
    - 45636332

cookie_domain: localhost
cookie_secure: false
jwt_secret: kappa123

frontend_domain: http://localhost:3000/admin
