version: "3.9"

services:
  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mongo:
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - mongo:/bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  redis:
  mongo:
