name: Build & Deploy (Production)

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    name: Build (Production)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log into Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.komodohype.dev
          username: robot$deploy
          password: ${{ secrets.REGISTRY_TOKEN }}

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            harbor.komodohype.dev/troy/yapper-controller:${{ github.sha }}
            harbor.komodohype.dev/troy/yapper-controller:latest
