name: Build & Deploy (Production)

on:
  push:
    branches: |
     - master
     - intro/*

  workflow_dispatch:

jobs:
  build:
    name: Build (Production)
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Log into Harbor Registry
        uses: docker/login-action@v1
        with:
          registry: harbor.komodohype.dev
          username: robot$deploy
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: setup docker context for buildx
        id: buildx-context
        run: |
          docker context create builders

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true
          endpoint: builders

      - name: Build Image
        id: build_step
        uses: docker/build-push-action@v2
        with:
          push: true
          network: host
          tags: |
            harbor.komodohype.dev/troy/yapper-controller:${{ github.sha }}
            harbor.komodohype.dev/troy/yapper-controller:latest
  deploy:
    name: Deploy (Production)
    runs-on: self-hosted
    needs: # Run this after build
      - build

    steps:
        # Checkout repository
        - uses: actions/checkout@v2

        # Deploy to k8s
        - name: Install kubectl&
          uses: azure/setup-kubectl@v1

        - name: Apply Deployment & Rollout
          env:
            KUBE_CONFIG_DATA: ${{ secrets.YAPPER_K8S_AUTODEPLOY }}
            KUBE_RESOURCE: deploy
            KUBE_IMAGE_PATCH: >-
              [
                { "op": "replace", "path": "/spec/template/spec/containers/0/image", "value": "harbor.komodohype.dev/troy/yapper-controller:${{ github.sha }}" }
              ]
          run: |
            mkdir -p ~/.kube
            (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
            kubectl config use-context autodeploy@yapper
            kubectl patch $KUBE_RESOURCE -n yapper controller --type="json" -p="$KUBE_IMAGE_PATCH"
            kubectl rollout restart -n yapper $KUBE_RESOURCE/controller
