name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - dev
  pull_request:
jobs:
  linting:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.6
      - uses: actions/cache@v2
        with:
          path: cache
          key: ${{ runner.os }}-linting
      - name: Linting
        run: export GOLANGCI_LINT_CACHE=$GITHUB_WORKSPACE/cache && export GOPATH=$GITHUB_WORKSPACE/cache && wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.41.1 && $GITHUB_WORKSPACE/bin/golangci-lint run --print-resources-usage --timeout 5m0s
